import type { Metadata } from "next";
import { UnifrakturMaguntia } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const satisfy = UnifrakturMaguntia({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "Fragments",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satisfy.variable} antialiased`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
